version: "3.8"
services: 
  mongodb:
    image: 'mongo'
    name: 'mongodb'
    network: 'goals-net'
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=max 
      - MONGO_INITDB_ROOT_PASSWORD=secret 
    volumes: 
      - data:/data/db
  backend:
  frontend:
